### ISSUE TITLE
Get i18n rolling

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticScribunto#1]
* [x] add repo to user group with push rights
* [x] review en.json and qqq.json
* [x] ping twn to add the repo
* [x] affirmation by twn that support was added

**Comment by kghbln** [comment]
@Nikerabbit Another new extension. It will be nice to have twn support.

**Comment by Nikerabbit** [comment]
It has been set up.

**Comment by kghbln** [comment]
Thanks again! I will keep this open until the first translations roll in.
