### ISSUE TITLE
Use IncomingSemanticDataValidator instead of `assertInProperties`

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticScribunto#30]
`SemanticScribuntoJsonTestCaseScriptRunnerTest` to replace `assertInProperties` with `IncomingSemanticDataValidator`.

refs #29, https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2161

**Comment by kghbln** [comment]
@mwjames I guess this should happen prior to https://github.com/SemanticMediaWiki/SemanticScribunto/issues/42
