### ISSUE TITLE
1.1.0 release 

### ISSUE THREAD

**Issue by oetterer** [SemanticMediaWiki/SemanticScribunto#42]
Isn't it time to switch from 1.1.0-alpha to 1.1.1?

**Comment by kghbln** [comment]
The last stable release was 1.0.0 so from looking at the code changes (include a minimum requirement bump) since that the next up is 1.1.0

**Comment by kghbln** [comment]
- [ ] Finalize release notes
- [ ] Update readme
- [ ] Update version number (1.1.0)
  - [ ] SemanticScribunto.php
- [ ] Create tag
- [ ] Announce via mail
- [ ] Do a release tweet on Twitter

**Comment by kghbln** [comment]
@mwjames Just give a GO and I could do the release first week of January 2018.

**Comment by kghbln** [comment]
@mwjames A little pro or con will be nice. Would you like to wait for https://github.com/SemanticMediaWiki/SemanticScribunto/issues/30 or may I do a release the upcoming week?

**Comment by mwjames** [comment]
> Would you like to wait for #30 or may I do a release the upcoming week?

#30 is only relevant for code quality therefore I'd say you can push the release.
