### ISSUE TITLE
mw.set drops property names with numbers in key-value mode

### ISSUE THREAD

**Issue by honestleaf** [SemanticMediaWiki/SemanticScribunto#48]
### Setup and configuration

- SMW version: 2.2.5
- SSC version: 1.0.0
- MW version: 1.30.0
- DB (MySQL etc.): MySQL

### Issue

When setting properties by using key-value form, if the "key" part contains numbers, then the property will not be accepted (more like simply get ignored).

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):
Using following table to setup properties. ([source](https://sandbox.semantic-mediawiki.org/wiki/Module:SmwLuaTest))
```
local settings = {
	['hello'] = 'world',
	['hell0'] = 'world',
	'HELLO=WORLD',
	'HELL0=WORLD',
}
```
Only ```['hell0'] = 'world'```  doesn't show up on [browse page](https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Honestleaf/SmwLuaTest).

**Comment by oetterer** [comment]
@kghbln could you please assign this issue to me.

**Comment by kghbln** [comment]
@oetterer This is apparently not so easy. I sent you some invitations via GitHub hopeing that this will allow me to select you. Touching wood.

**Comment by oetterer** [comment]
Worked fine, thank you. 👍  Courious, that you couldn't find me in assignees....

**Comment by kghbln** [comment]
You probably had to be part of a group with extra powers. :)
