### ISSUE TITLE
mw.smw.set should recognize multiple values for one property given in a sub-table

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticScribunto#55]
### Setup and configuration

- SMW version: 2.5.6
- SSC version: 1.1.1
- MW version: 1.30
- DB (MySQL etc.): 10.0.34-MariaDB

### Issue

`mw.smw.set()` allows setting multiple values for the same property by having arguments like
```
table#1 { 
  "prop=value", 
  "prop=value2", 
}
```

It would be great if it could handle arguments of the form
```
table#1 { 
  ["prop"] = table#2 { 
    "value",
    "value2", 
  }, 
}
```

(This is also the format returned by `mw.smw.ask()` when the result has multiple values for one property.)

**Comment by kghbln** [comment]
I will do a 1.2.0 release probably on Wednesday if there are no objections from any of you.
