### ISSUE TITLE
Object of class LuaSandboxFunction could not be converted to string when passing iterators into SMW objects

### ISSUE THREAD

**Issue by FO-nTTaX** [SemanticMediaWiki/SemanticScribunto#75]
### Setup and configuration

- SMW version: `3.1.0`
- SSC version: `2.1.0`
- MW version: `1.31.5`
- DB (MySQL etc. and version): `10.4.10-MariaDB-1:10.4.10+maria~buster`
- `7.3.11-1+0~20191026.48+debian9~1.gbpf71ca0 (fpm-fcgi)`

### Issue
When people create modules that save bad values into Semantic Objects, the calling page errors out as HTTP error 500. In the example someone tried to save an iterator into a property, which obviously does not work, getting an error 500 instead of an error message was not very obvious to them though. Returning an error message instead of a hard error 500 would probably be advisable.

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
PHP Recoverable fatal error:  Object of class LuaSandboxFunction could not be converted to string in /extensions/SemanticScribunto/src/ScribuntoLuaLibrary.php on line 363
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Example Module:
```
local p = {}
function p.t()
	local dataStore = {}
	dataStore['some property'] = mw.text.gsplit('some','strings')
	mw.smw.set(dataStore)
	-- mw.smw.subobject(dataStore) -- this produces the same result
end
return p
```
and the module would simply be called as `{{#invoke:Module name|t}}`

Given it is easy to work around this by not passing broken things in, I do not think this is super urgent, but it might be a nice to have to catch such errors.

**Comment by kghbln** [comment]
@FO-nTTaX Thanks for reporting and suggesting. I agree that a more graceful failure will be preferable.

@oetterer FYI Probably you would like to have a go at it. :)
