### ISSUE TITLE
API query does not work for wikis that require login to read

### ISSUE THREAD

**Issue by cicalese** [SemanticMediaWiki/SemanticScribunto#8]
### Setup and configuration
- SMW version: 2.4.1
- SSO version: 1.0
- MW version: 1.26
- DB (MySQL etc.): MySQL
### Issue

SemanticScribunto uses the ask API to make the query. This does not work when the wiki requires login to read. SemanticScribunto could either go through the login flow to make the API request (probably more trouble than it is worth) or make the query directly in PHP without using the API.

[0d9efd17] [no req]   UsageException from line 1368 of .../includes/api/ApiBase.php: You need read permission to use this module
### Backtrace

```
#0 .../includes/api/ApiBase.php(1956): ApiBase->dieUsage(string, string)
#1 .../includes/api/ApiMain.php(1180): ApiBase->dieUsageMsg(string)
#2 .../includes/api/ApiMain.php(1251): ApiMain->checkExecutePermissions(SMW\MediaWiki\Api\Ask)
#3 .../includes/api/ApiMain.php(436): ApiMain->executeAction()
#4 .../extensions/SemanticScribunto/src/ScribuntoLuaLibrary.php(57): ApiMain->execute()
#5 [internal function]: SMW\Scribunto\ScribuntoLuaLibrary->getQueryResult(string)
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

Set the following in the wiki configuration file:

`$wgGroupPermissions['*']['read'] = false;`

Attempt to use SemanticScribunto.

**Comment by cicalese** [comment]
A clarification on this issue. The error occurs when running refreshLinks, since there is no wiki user associated with the context.

**Comment by mwjames** [comment]
>  This does not work when the wiki requires login to read.

That reminds me of [0].

> or make the query directly in PHP without using the API.

Classes in `SMW\MediaWiki\*` are private so I cannot (by convention) call them outside of SMW-core and I don't think that copying code is the best possible choice. 

The API already does the job so I'd like to avoid yet another implementation that copies code and carries the maintenance burden. There must be a way in MW to get around this issue otherwise what's the API good for! 

>  wiki requires login to read. SemanticScribunto could either go through the login flow

I'd be happy to do something about given some simple examples are provided that would make the whole "API/login" a non exploratory exercise especially after 1.27+.

[0] https://github.com/SemanticMediaWiki/SemanticExternalQueryLookup/issues/28

**Comment by cicalese** [comment]
Agreed, I had seen the SemanticExternalQueryLookup issue. They are similar in that both issues are related to API login. The big difference is that SemanticExternalQueryLookup, by definition, needs to work remotely, but SemanticScribunto usage is contained within the bounds of a single wiki. In the single wiki case, API usage is burdened by its need to support remote invocation and, thus, login. I am sympathetic to the need to limit access to Semantic MediaWiki code internals, but I would think that there are some outward facing classes whose interface is relatively stable for usage by other extensions. The alternative would be to have SemanticScribunto detect the API login failure and die gracefully so as not to keep refreshLinks from completing. But that would not include any data returned from the API query in the refreshed pages.

**Comment by mwjames** [comment]
> I am sympathetic to the need to limit access to Semantic MediaWiki code internals, but I would think that there are some outward facing classes whose interface

**Without** having tested it, something like below should get the same result as when using the "action" API.

```php
use SMWQueryProcessor as QueryProcessor;
use SMW\ApplicationFactory;


function getQueryResultAsJsonFrom( $string ) {

	$rawParameters = preg_split( "/(?<=[^\|])\|(?=[^\|])/", $string );

	list( $queryString, $parameters, $printouts ) = QueryProcessor::getComponentsFromFunctionParams(
		$rawParameters,
		false
	);

	QueryProcessor::addThisPrintout( $printouts, $parameters );

	$query = QueryProcessor::createQuery(
		$queryString,
		QueryProcessor::getProcessedParams( $parameters, $printouts ),
		QueryProcessor::SPECIAL_PAGE,
		'',
		$printouts
	);

	$queryResult = ApplicationFactory::getInstance()->getStore()->getQueryResult( $query );

	return json_encode(
		$queryResult->toArray(),
		JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
	)

}
```

>  I would think that there are some outward facing classes whose interface is relatively stable for usage by other extensions.

There are but several of them have design issues (I'm avoiding the discussion here on why, where etc.), let's stay focused on the topic at hand.

> The alternative would be to have SemanticScribunto detect the API login failure and die gracefully so as not to keep refreshLinks from completing. 

That's not really an alternative but yes, if at all this should be handled more gracefully. Again there needs to be a way using the MW "action" API and not fail at this point.

**Comment by matthew-a-thompson** [comment]
I've created a pull request based on the above code that should resolve this issue. This change modifies the getQueryResult method to use QueryProcessor and ApplicationFactory as above, while still returning a result object that is more or less the same as getQueryResult was returning from the API call. The main difference in the result objects is that the result set used to be located at $queryResult["query"]["results"] and is now located at $queryResult["results"]. #9

**Comment by kghbln** [comment]
So this issue is fixed now?

**Comment by cicalese** [comment]
Yes :-)
