### ISSUE TITLE
Bubble "error" in mw.smw.info is broken

### ISSUE THREAD

**Issue by Ostrzyciel** [SemanticMediaWiki/SemanticScribunto#82]
### Setup and configuration

- SMW version: 3.2.2
- SSC version: 2.2.0
- MW version: 1.35.1
- DB (MySQL etc. and version): doesn't matter here

### Issue

When `mw.smw.info` is called with `error` as its second parameter, instead of a red icon specified in [the docs](https://www.semantic-mediawiki.org/wiki/Help:Adding_tooltips), a default `info` type icon appears.

That should be easy to fix, I'll submit a patch soon.

**Comment by kghbln** [comment]
@Ostrzyciel Thanks for reporting and providing a fix soon. @oetterer It will be cool if you could have a look at the patch once it is there.

**Comment by Ostrzyciel** [comment]
Could someone merge this? It's a trivial fix and I've even provided a unit test for this.
