### ISSUE TITLE
Not working with MW 1.42

### ISSUE THREAD

**Issue by keepersdungeon** [SemanticMediaWiki/SemanticScribunto#95]
### Setup and configuration

- SMW version:4.1.3
- SSC version:2.2
- MW version:1.42
- DB (MySQL etc. and version):  10.6.16-MariaDB-cll-lve

### Issue
SSC doesn't seem to work with MW1.42 when upgrading. SMW alone seems fine but when I enable SSC and re-update MW doesn't load up

**Comment by harugon** [comment]
It seems that the fix provided in [PR #94](https://github.com/SemanticMediaWiki/SemanticScribunto/pull/94) has not been included in a release yet. Could you please create a new release that includes this fix? This would greatly help those of us who are upgrading to MediaWiki 1.42.

Thank you for your hard work and support!

Best regards,

**Comment by tr1age** [comment]
In the same boat.
Scribunto Works.
SMW works
Enable SemanticScribunto and 
Fatal error: Uncaught UnexpectedValueException: callback 'SemanticScribunto::initExtension' is not callable in /home/u641889600/domains/uoalive.com/public_html/wiki/includes/registration/ExtensionRegistry.php:559 Stack trace: #0 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/registration/ExtensionRegistry.php(320): ExtensionRegistry->exportExtractedData() #1 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/Setup.php(288): ExtensionRegistry->loadFromQueue() #2 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/WebStart.php(85): require_once('/home/u64188960...') #3 /home/u641889600/domains/uoalive.com/public_html/wiki/index.php(50): require('/home/u64188960...') #4 {main} thrown in /home/u641889600/domains/uoalive.com/public_html/wiki/includes/registration/ExtensionRegistry.php on line 559

**Comment by oetterer** [comment]
Thanks for the reports. I look into it. Unfortunately, I first need to fix ci.

**Comment by oetterer** [comment]
commit e06b9033cc875668eb6353ecaac87ff8177a1b85 should address the mentioned issues, SSC version 2.3.0 now works with MW core 1.39+.

BUT: SMW itself currently has problems with core 1.42. See SemanticMediaWiki/SemanticMediaWiki/#5634

**Comment by tr1age** [comment]
Did you add this to core? Thank you got such a quick turn around!

**Comment by oetterer** [comment]
@tr1age sry, meant to say that SemanticMediawiki apparently runs into database problems on MediaWiki 1.42 and 1.43. And these problems also affect SemanticScribunto, since this extension relies on SMW to function.

**Comment by tr1age** [comment]
@oetterer Oh, crap. Yeah my issue is it says I have pygments installed but then it does nothing. I did get Scribunto to run with my own edits. But I am not sure it is doing anything.

**Comment by oetterer** [comment]
if possible, I would suggest to stay at mediawiki 1.41, or better yet use the current LTS 1.39. SMW and SSC do work with these version.

**Comment by tr1age** [comment]
![image](https://github.com/user-attachments/assets/3f587e78-72a1-4062-b530-1ecde2c8fb74)
This is where I am at. We just started using Media wiki days ago so it gave us that version

**Comment by oetterer** [comment]
If you havent invested much, I strongly recomment using the LTS (1.39). You have much better compatibility in generell for most extensions. Normally, you dont need the latest, freshest features from the "in-between-version" and it is totally reasonable to hop from LTS to LTS. Most people who run a productive mediawiki installation do this. Much less headache.

**Comment by tr1age** [comment]
We put a lot of info in there already. We move fast https://uoalive.com/wiki/Special:Version. what is LTS?

**Comment by oetterer** [comment]
![grafik](https://github.com/user-attachments/assets/3eb8d708-f9f1-4417-a3dc-197f24ffbb6f)

It's the "Long Term Support" Version. Wikimedia Foundation promisses to support the legacy branches for 1 year and the LTS branches for 3 year. Every fourth release is an LTS release (1.35, 1,39, 1.43, etc.). Therefore you can run your MediaWiki installation stable, bug- and security issues free for 3 years before you need to upgrade to a new core version. Otherwise, you would need to upgrade every year.

**Comment by tr1age** [comment]
WOW! The things you learn. Thank you for this. So with the stable.... is that not LTS? like how do upgrades work on that? Oh boy... I didn't know this...

**Comment by oetterer** [comment]
Just visited your wiki, looks really nice. Theoretically, there is a way to "downgrade". You could do an xml export of **all** your pages (in main, template, module and all your custom namespaces). Then you could scrap your current installation, make a fresh one with 1.39 and import all the xml files.

You could also try and run a 1.39 installation on your current database, maybe 1.42 database schema is compatible with 1.39. Though I woudn't recomment this.

> WOW! The things you learn. Thank you for this. So with the stable.... is that not LTS? like how do upgrades work on that? Oh boy... I didn't know this...

No, stable is not LTS. Wikimedia Foudation always develops new features or does refactoring work on master branch. Once, all the desired features and work is done, they call a feature stop. Then all (discovered) bugs get fixed and a new stable version is set. The old stable becomes legacy and new features on master gets to be developed for the next stable. Every fourth version gets a longer support windows and will be maintained for three instead of one year.

**Comment by tr1age** [comment]
Thank you! We have been working really hard on it.

So technically we have a year of support on this version.. then what happens? "get smart" explosion type deal lol

**Comment by tr1age** [comment]
BTW just tested your new Scribunto 

Fatal error: Uncaught InvalidArgumentException: It was attempted to load SemanticScribunto twice, from /home/u641889600/domains/uoalive.com/public_html/wiki/extensions/SemanticScribunto/extension.json and /home/u641889600/domains/uoalive.com/public_html/wiki/extensions/Scribunto/extension.json. in /home/u641889600/domains/uoalive.com/public_html/wiki/includes/registration/ExtensionProcessor.php:790 Stack trace: #0 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/registration/ExtensionProcessor.php(275): ExtensionProcessor->extractCredits() #1 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/registration/ExtensionRegistry.php(452): ExtensionProcessor->extractInfo() #2 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/registration/ExtensionRegistry.php(317): ExtensionRegistry->readFromQueue() #3 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/Setup.php(288): ExtensionRegistry->loadFromQueue() #4 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/WebStart.php(85): require_once('/home/u64188960...') #5 /home/u641889600/domains/uoalive.com/public_html/wiki/index.php(50): require('/home/u64188960...') #6 {main} thrown in /home/u641889600/domains/uoalive.com/public_html/wiki/includes/registration/ExtensionProcessor.php on line 790

**Comment by tr1age** [comment]
Just attemtped your new version of semanticscribunto:


Warning: require(/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/../../extensions/SemanticScribunto/SemanticScribunto.php): Failed to open stream: No such file or directory in /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/autoload_real.php on line 45

Fatal error: Uncaught Error: Failed opening required '/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/../../extensions/SemanticScribunto/SemanticScribunto.php' (include_path='/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/console_getopt:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/mail:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/mail_mime:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/net_smtp:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/net_socket:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/net_url2:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/pear-core-minimal/src:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/pear_exception:.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/autoload_real.php:45 Stack trace: #0 /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/autoload_real.php(49): {closure}() #1 /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/autoload.php(25): ComposerAutoloaderInit_mediawiki_vendor::getLoader() #2 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/AutoLoader.php(298): require_once('/home/u64188960...') #3 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/Setup.php(121): require_once('/home/u64188960...') #4 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/WebStart.php(85): require_once('/home/u64188960...') #5 /home/u641889600/domains/uoalive.com/public_html/wiki/index.php(50): require('/home/u64188960...') #6 {main} thrown in /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/autoload_real.php on line 45

**Comment by oetterer** [comment]
> Thank you! We have been working really hard on it.
> 
> So technically we have a year of support on this version.. then what happens? "get smart" explosion type deal lol

The problem is much less the "only one year support" but more the problem with heavy hitter extensions like SemanticMediaWiki. They tend to need the full 3years from LTS to LTS to get compatible with the new version. Especially SMW, witch is afaik the most compley extension there is in the MW universe.

**Comment by oetterer** [comment]
> Just attemtped your new version of semanticscribunto:
> 
> Warning: require(/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/../../extensions/SemanticScribunto/SemanticScribunto.php): Failed to open stream: No such file or directory in /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/autoload_real.php on line 45
> 
> Fatal error: Uncaught Error: Failed opening required '/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/../../extensions/SemanticScribunto/SemanticScribunto.php' (include_path='/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/console_getopt:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/mail:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/mail_mime:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/net_smtp:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/net_socket:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/net_url2:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/pear-core-minimal/src:/home/u641889600/domains/uoalive.com/public_html/wiki/vendor/pear/pear_exception:.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/autoload_real.php:45 Stack trace: #0 /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/autoload_real.php(49): {closure}() #1 /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/autoload.php(25): ComposerAutoloaderInit_mediawiki_vendor::getLoader() #2 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/AutoLoader.php(298): require_once('/home/u64188960...') #3 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/Setup.php(121): require_once('/home/u64188960...') #4 /home/u641889600/domains/uoalive.com/public_html/wiki/includes/WebStart.php(85): require_once('/home/u64188960...') #5 /home/u641889600/domains/uoalive.com/public_html/wiki/index.php(50): require('/home/u64188960...') #6 {main} thrown in /home/u641889600/domains/uoalive.com/public_html/wiki/vendor/composer/autoload_real.php on line 45

Try `composer dump-autoload`or edit `vendor/composer/autoload_static.php`and remove the SemanticScribunto.php-reference in the `array public static $files`.

**Comment by tr1age** [comment]
Yeah Im sorry im dumb. I am so new to this. I didn't run composer. :P

**Comment by oetterer** [comment]
Please don't say that. MediaWiki is a complex beast and there is a long learning curve! Took me several years,

**Comment by tr1age** [comment]
This however is interesting. 
![image](https://github.com/user-attachments/assets/87e72cf0-b04c-4e13-9db1-688c89fb313f)
and yeah it is really powerful but also really difficult. I liked Wiki.JS but it's kinda becoming vaporware.

**Comment by oetterer** [comment]
> Yeah Im sorry im dumb. I am so new to this. I didn't run composer. :P What does composer dump-autoload do?

composer maintains a list of all the classes and files in its autoloader. That is a system that automatically loads a classes sourcefile, once a class is referenced. Old SSC had a class that needed to loaded hard on extension activation. I got rid of this on 2.3.0, but failed to just leave an empty file at the old location to mitigate any composer errors.

**Comment by oetterer** [comment]
> This however is interesting. ![image](https://private-user-images.githubusercontent.com/3319999/349266845-87e72cf0-b04c-4e13-9db1-688c89fb313f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNjIzMTcsIm5iZiI6MTcyMTE2MjAxNywicGF0aCI6Ii8zMzE5OTk5LzM0OTI2Njg0NS04N2U3MmNmMC1iMDRjLTRlMTMtOWRiMS02ODhjODlmYjMxM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMjAzMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQyMTRhN2M5ZDU4NWZlZjQ5ZjA2NzQzODllMjhkZDZlOTExNmU0NzhhN2RlOTkyODhlMTM5NGEyM2FlYmUwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VIB9nmXDrSAoGxI2gAyeMJlyQIDKo46npr8eY5DcS0w) and yeah it is really powerful but also really difficult. I liked Wiki.JS but it's kinda becoming vaporware.

Hmm. Look like a small problem with the messages. Thanks for pointing this out,

**Comment by tr1age** [comment]
YAY I WAS HELPFUL! haha and thanks again for helping and not being "above it" really nice of you if you want add me to discord "tr1age"

**Comment by oetterer** [comment]
Sry, I'm not really active on discord. But thanks for the offer, really nice of you!

**Comment by oetterer** [comment]
2.3.1 (b349c65efd7a3a745cc98c7617b1bd0c9a22059d) will fix the missing messages.

**Comment by kghbln** [comment]
@oetterer Should 2.3.1 be tagged now? If so, we must add some info about 2.3.1 to the release notes.

**Comment by oetterer** [comment]
@kghbln Sry, I'm not sure, what you mean. I tagged the version in git and put the new version number on https://www.mediawiki.org/wiki/Extension:Semantic_Scribunto. In the install instructions it says `"mediawiki/semantic-scribunto": "~2.3"` which includes the 2.3.1. What did I miss?

**Comment by kghbln** [comment]
@oetterer Ah, senior moments. I looked at the releases rather than the tags. Yeah, tagging was done. :) Still, some info about both in the [release notes](https://github.com/SemanticMediaWiki/SemanticScribunto/blob/master/RELEASE-NOTES.md) is still missing.
